import random


class User:
    def __init__(self, user_id):
        self.num = user_id
        self.current_kanji = 0
        self.current_word = 0
        self.word_mod = 0
        self.isTalking = 0

    def change_word_mod(self, word_mod):
        self.word_mod = word_mod


users = dict()


def get_user(user_id):
    return users[user_id]


def add_user(user_id):
    user = User(user_id)
    users[user.num] = user


class Kanji:
    def __init__(self, kanji, reading, lvl, image_url):
        self.kanji = kanji
        self.readings = reading
        self.words = []
        self.lvl = lvl
        self.image_url = image_url

    def get_image_url(self):
        return self.image_url


class Word:
    def __init__(self, word, writening, translation):
        self.word = word
        self.reading = writening
        self.translation = translation

    def get_mod(self, word_mod):
        if word_mod == 'by_original':
            return self.word
        if word_mod == 'by_reading':
            return self.reading
        else:
            return self.translation


def kanji_handler(text, chat_id):
    current_kanji = get_user(chat_id).current_kanji
    if current_kanji == 0:
        current_kanji = get_user(chat_id).current_kanji = random.choice(kanji_list)
    if text == 'Новый кандзи':
        current_kanji = get_user(chat_id).current_kanji = random.choice(kanji_list)
        return current_kanji.kanji
    elif text == 'Чтение':
        txt = current_kanji.kanji + '\n'
        for reading in current_kanji.readings:
            txt += '\n' + reading
        return txt
    elif text == 'Слова с этим кандзи':
        txt = current_kanji.kanji + '\n'
        i = 1
        for word in current_kanji.words:
            txt += '\n\n' + str(
                i) + '.' + ' ' + word.word + ' ' + '(' + word.reading + ')' + ' ' + '—' + ' ' + word.translation
            i += 1
        return txt
    elif text == 'Порядок черт':
        return current_kanji.image_url
    else:
        return 'Error'


def word_handler(text, chat_id):
    current_word = get_user(chat_id).current_word
    if current_word == 0:
        current_word = users[chat_id].current_word = random.choice(word_list)
    mod = get_user(chat_id).word_mod
    if text == 'Дальше':
        current_word = users[chat_id].current_word = random.choice(word_list)
        return current_word.get_mod(mod)
    elif text == 'Чтение':
        return current_word.reading
    elif text == 'Перевод':
        return current_word.translation
    elif text == 'Слово':
        return current_word.word
    else:
        return 'Error'


kanji_list = \
    (Kanji('場', ['ば', 'ジョウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/32/ba/_a.gif'),
     Kanji('工', ['コウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/48/_a.gif'),
     Kanji('家', ['いえ', 'や', 'カ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/40/kazoku/_a.gif'),
     Kanji('族', ['ゾク'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/70/zoku/_a.gif'),
     Kanji('兄', ['あに', 'ケイ', 'キョウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/10/ani/_a.gif'),
     Kanji('弟', ['おとうと', 'テイ', 'ダイ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/57/otouto/_a.gif'),
     Kanji('姉', ['あね', 'シ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/38/ane/_a.gif'),
     Kanji('妹', ['いもうと', 'マイ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/38/imouto/_a.gif'),
     Kanji('私', ['わたし', 'シ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/115/watashi/_a.gif'),
     Kanji('育', ['そだつ', 'そだーつ', 'そだーてる', 'イク'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/130/sodatsu/_a.gif'),
     Kanji('部', ['ブ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/163/bu/_a.gif'),
     Kanji('屋', ['や', 'オク'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/44/heya/_a.gif'),
     Kanji('広', ['ひろーがる', 'ひろーげる', 'ひろーい', 'コウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/53/hiroi/_a.gif'),
     Kanji('低', ['ひくーい', 'ひくーい', 'テイ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/9/tei/_a.gif'),
     Kanji('緑', ['みどり', 'リョク'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/120/midori/_a.gif'),
     Kanji('静', ['しずーか', 'セイ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/174/sei/_a.gif'),
     Kanji('近', ['ちかーい', 'キン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/162/chikai/_a.gif'),
     Kanji('遠', ['とおーい', 'エン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/162/tooi/_a.gif'),
     Kanji('会', ['あーう', 'カイ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/9/au/_a.gif'),
     Kanji('社', ['シャ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/113/yashiro/_a.gif'),
     Kanji('働', ['はたらーく', 'ドウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/9/hataraku/_a.gif'),
     Kanji('作', ['つくーる', 'サク', 'サ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/9/tsukuru/_a.gif'),
     Kanji('始', ['はじーまる', 'はじーめる', 'シ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/38/hajimaru/_a.gif'),
     Kanji('終', ['おーわる', 'おーえる', 'ショウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/120/owaru/_a.gif'),

     Kanji('店', ['みせ', 'テン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/53/mise/_a.gif'),
     Kanji('客', ['キャク', 'カク'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/40/kyaku/_a.gif'),
     Kanji('親', ['したーしい', 'おや', 'シン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/147/oya/_a.gif'),
     Kanji('切', ['きる', 'セツ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/18/kiru/_a.gif'),
     Kanji('売', ['うーる', 'うーれる', 'バイ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/33/bai/_a.gif'),
     Kanji('当', ['あーたる', 'あーてる', 'トウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/42/ateru/_a.gif'),
     Kanji('品', ['しな', 'ヒン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/30/hin/_a.gif'),
     Kanji('便', ['たよーり', 'ベン', 'ビン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/9/tayori/_a.gif'),
     Kanji('利', ['リ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/18/ri/_a.gif'),
     Kanji('使', ['つかーう', 'シ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/9/tsukau/_a.gif'),
     Kanji('銀', ['ギン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/167/gin/_a.gif'),
     Kanji('白', ['しろーい', 'しろ', 'ハク'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/106/shiroi/_a.gif'),
     Kanji('黒', ['くろーい', 'くろ', 'コク'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/203/_a.gif'),
     Kanji('紙', ['かみ', 'シ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/120/kami/_a.gif'),
     Kanji('朝', ['あさ', 'チョウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/74/asa/_a.gif'),
     Kanji('晩', ['バン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/72/ban/_a.gif'),
     Kanji('昼', ['ひる', 'チュウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/44/hiru/_a.gif'),
     Kanji('夜', ['よる', 'よ', 'ヤ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/36/yoru/_a.gif'),
     Kanji('前', ['まえ', 'ゼン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/18/mae/_a.gif'),
     Kanji('後', ['うしーろ', 'あと', 'ゴ', 'コウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/60/ushiro/_a.gif'),
     Kanji('午', ['ゴ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/24/go/_a.gif'),
     Kanji('早', ['はやーい', 'ソウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/72/hayai/_a.gif'),
     Kanji('荷', ['に'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/140/ni/_a.gif'),
     Kanji('送', ['おくーる', 'ソウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/162/okuru/_a.gif'),
     Kanji('宅', ['タク'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/40/taku/_a.gif'),
     Kanji('急', ['いそーぐ', 'キュウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/61/isogu/_a.gif'),
     Kanji('速', ['はやーい', 'ソク'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/162/soku/_a.gif'),
     Kanji('遅', ['おくーれる', 'おそーい', 'チ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/162/osoi/_a.gif'),
     Kanji('重', ['かさーなる', 'かさーねる', 'おもーい', 'ジュウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/166/omoi/_a.gif'),
     Kanji('軽', ['かるーい', 'かろーやか', 'ケイ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/159/karui/_a.gif'),
     Kanji('住', ['すーむ', 'ジュウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/9/sumu/_a.gif'),
     Kanji('所', ['ところ', 'ショ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/63/tokoro/_a.gif'),
     Kanji('様', ['さま', 'ヨウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/75/you/_a.gif'),
     Kanji('主', ['めし', 'おも', 'シュ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/3/nushi/_a.gif'),
     Kanji('番', ['バン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/102/ban/_a.gif'),
     Kanji('地', ['チ', 'ジ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/32/chi/_a.gif'),
     Kanji('号', ['ゴウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/30/gou/_a.gif'),
     Kanji('京', ['キョウ', 'ケイ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/8/miyako/_a.gif'),
     Kanji('都', ['みやこ', 'ト'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/163/tsu/_a.gif'),
     Kanji('道', ['みち', 'ドウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/162/michi/_a.gif'),
     Kanji('府', ['フ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/53/fu/_a.gif'),
     Kanji('県', ['ケン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/109/ken/_a.gif'),
     Kanji('市', ['いち', 'シ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/50/shi/_a.gif'),
     Kanji('区', ['ク'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/23/ku/_a.gif'),
     Kanji('村', ['むら', 'ソン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/75/mura/_a.gif'),
     Kanji('毎', ['マイ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/80/mai/_a.gif'),
     Kanji('週', ['シュウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/162/shuu/_a.gif'),
     Kanji('映', ['うつーる', 'うつーす', 'エイ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/72/utsuru/_a.gif'),
     Kanji('画', ['ガ', 'カク'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/102/kaku/_a.gif'),
     Kanji('図', ['ズ', 'ト'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/31/hakaru/_a.gif'),
     Kanji('館', ['カン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/184/kan/_a.gif'),
     Kanji('公', ['おおやけ', 'コウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/12/kou/_a.gif'),
     Kanji('園', ['エン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/31/sono/_a.gif'),
     Kanji('夫', ['おっと', 'フ', 'フウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/37/otto/_a.gif'),
     Kanji('妻', ['つま', 'サイ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/38/sai/_a.gif'),
     Kanji('特', ['トク'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/93/toku/_a.gif'),
     Kanji('思', ['おもーい', 'シ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/61/omou/_a.gif'),
     Kanji('料', ['リョウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/68/ryou/_a.gif'),
     Kanji('理', ['リ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/96/ri/_a.gif'),
     Kanji('有', ['ユウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/74/aru/_a.gif'),
     Kanji('洋', ['ヨウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/85/you/_a.gif'),
     Kanji('服', ['フク'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/74/fuku/_a.gif'),
     Kanji('衣', ['ころも', 'イ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/145/_a.gif'),
     Kanji('短', ['みじかーい', 'タン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/111/mijikai/_a.gif'),
     Kanji('毛', ['け', 'モウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/82/_a.gif'),
     Kanji('糸', ['いと'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/120/_a.gif'),
     Kanji('玉', ['たま'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/96/gyoku/_a.gif'),
     Kanji('光', ['ひカーる', 'ひかり', 'コウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/10/hikaru/_a.gif'),
     Kanji('駅', ['エキ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/187/eki/_a.gif'),
     Kanji('鉄', ['テツ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/167/tetsu/_a.gif'),
     Kanji('乗', ['のーる', 'のーせる', 'ジョウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/4/noru/_a.gif'),
     Kanji('降', ['おーりる', 'おーろす', 'ふーる', 'コウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/170/oriru/_a.gif'),
     Kanji('開', ['あーく', 'あーける', 'ひらーく', 'カイ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/169/akeru/_a.gif'),
     Kanji('閉', ['しーまる', 'しーめる', 'とーじる', 'ヘイ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/169/hei/_a.gif'),
     Kanji('発', ['ハツ', 'ホツ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/105/hatsu/_a.gif'),
     Kanji('着', ['きーる', 'つーく', 'チャク'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/123/kiseru/_a.gif'),
     Kanji('交', ['まじーわる', 'まじーえる', 'まーじる', 'まーざる', 'まーぜる', 'コウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/8/kawasu/_a.gif'),
     Kanji('通', ['とおーる', 'かよーう', 'ツウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/162/tooru/_a.gif'),
     Kanji('台', ['ダイ', 'タイ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/30/dai/_a.gif'),
     Kanji('止', ['とーまる', 'とーめる', 'シ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/77/_a.gif'),
     Kanji('色', ['いろ', 'ショク'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/139/_a.gif'),
     Kanji('赤', ['あかーい', 'あか', 'セキ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/155/_a.gif'),
     Kanji('黄', ['き', 'オウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/201/_a.gif'),
     Kanji('青', ['あおーい', 'あお', 'セイ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/174/_a.gif'),
     Kanji('病', ['ビョウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/104/yamai/_a.gif'),
     Kanji('院', ['イン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/170/in/_a.gif'),
     Kanji('医', ['イ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/22/i/_a.gif'),
     Kanji('科', ['カ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/115/ka/_a.gif'),
     Kanji('薬', ['くすり', 'ヤク'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/140/kusuri/_a.gif'),
     Kanji('待', ['まーつ', 'タイ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/60/matsu/_a.gif'),
     Kanji('合', ['あーう', 'あーわす', 'あーわせる', 'ゴウ', 'カッ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/30/au/_a.gif'),
     Kanji('計', ['はかーる', 'ケイ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/149/hakaru/_a.gif'),
     Kanji('研', ['ケン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/112/togu/_a.gif'),
     Kanji('究', ['キュウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/116/kyuu/_a.gif'),
     Kanji('語', ['かたーる', 'ゴ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/149/kataru/_a.gif'),
     Kanji('文', ['ブン', 'モン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/67/_a.gif'),
     Kanji('英', ['エイ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/140/ei/_a.gif'),
     Kanji('化', ['カ', 'ケ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/21/bakeru/_a.gif'),
     Kanji('数', ['かぞーえる', 'かず', 'スウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/66/kazu/_a.gif'),
     Kanji('心', ['こころ', 'シン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/61/_a.gif'),
     Kanji('若', ['わかーい'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/140/wakai/_a.gif'),
     Kanji('集', ['あつーまる', 'あつーめる', 'シュウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/172/atsumeru/_a.gif'),
     Kanji('知', ['しーる', 'チ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/111/shiru/_a.gif'),
     Kanji('酒', ['さけ', 'さか', 'シュ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/164/sake/_a.gif'),
     Kanji('歌', ['うたーう', 'うた', 'カ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/76/utau/_a.gif'),
     Kanji('声', ['こえ', 'セイ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/33/koe/_a.gif'),
     Kanji('楽', ['たのーしむ', 'たのーしい', 'ラク', 'ガク'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/75/tanoshii/_a.gif'),
     Kanji('味', ['あじーわう', 'あじ', 'ミ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/30/aji/_a.gif'),
     Kanji('油', ['あぶら', 'ユ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/85/abura/_a.gif'),
     Kanji('太', ['ふとーる', 'ふとーい', 'タイ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/37/futoi/_a.gif'),
     Kanji('細', ['ほそーい', 'こまーかい', 'サイ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/120/hosoi/_a.gif'),
     Kanji('皿', ['さら'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/108/_a.gif'),
     Kanji('飯', ['めし', 'ハン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/184/meshi/_a.gif'),
     Kanji('麦', ['むぎ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/34/baku/_a.gif'),
     Kanji('春', ['はる', 'シュン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/72/haru/_a.gif'),
     Kanji('夏', ['なつ', 'カ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/34/natsu/_a.gif'),
     Kanji('秋', ['あき', 'シュウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/115/aki/_a.gif'),
     Kanji('冬', ['ふゆ', 'トウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/15/fuyu/_a.gif'),
     Kanji('空', ['あーく', 'あーける', 'そら', 'ぞら', 'クウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/116/kara/_a.gif'),
     Kanji('星', ['ほし', 'セイ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/72/hoshi/_a.gif'),
     Kanji('雲', ['くも', 'ウン'],
           4, 'https://nihongoichibandotcom.files.wordpress.com/2011/06/96f2.gif'),
     Kanji('去', ['さーる', 'キョ', 'コ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/28/saru/_a.gif'),
     Kanji('天', ['テン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/37/ten/_a.gif'),
     Kanji('晴', ['はーれる', 'セイ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/72/hareru/_a.gif'),
     Kanji('雪', ['ゆき', 'セツ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/173/setsu/_a.gif'),
     Kanji('風', ['かぜ', 'フウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/182/_a.gif'),
     Kanji('強', ['つよーまる', 'つよーめる', 'つよーい', 'キョウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/57/tsuyoi/_a.gif'),
     Kanji('弱', ['よわーる', 'よわーまる', 'よわーめる', 'よわーい', 'ジャク'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/57/jaku/_a.gif'),
     Kanji('暑', ['あつーい', 'ショ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/72/atsui/_a.gif'),
     Kanji('寒', ['さむーい', 'カン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/40/samui/_a.gif'),
     Kanji('旅', ['たび', 'リョ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/70/tabi/_a.gif'),
     Kanji('待', ['まーつ', 'ジ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/60/matsu/_a.gif'),
     Kanji('世', ['よ', 'セイ', 'セ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/1/sei/_a.gif'),
     Kanji('界', ['カイ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/102/kai/_a.gif'),
     Kanji('写', ['うつーる', 'うつーす', 'シャ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/14/utsusu/_a.gif'),
     Kanji('真', ['ま', 'シン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/109/ma/_a.gif'),
     Kanji('船', ['ふね', 'セン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/137/sen/_a.gif'),
     Kanji('勉', ['ベン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/19/ben/_a.gif'),
     Kanji('漢', ['カン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/85/kan/_a.gif'),
     Kanji('宿', ['やど', 'シュク'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/40/yado/_a.gif'),
     Kanji('題', ['ダイ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/181/dai/_a.gif'),
     Kanji('質', ['シツ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/154/shichi/_a.gif'),
     Kanji('問', ['とーう', 'とーい', 'モン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/30/mon/_a.gif'),
     Kanji('教', ['おしーえる', 'おそーわる', 'キョウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/66/oshieru/_a.gif'),
     Kanji('室', ['シツ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/40/muro/_a.gif'),
     Kanji('試', ['ためーす', 'こころーみる', 'シ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/149/tamesu/_a.gif'),
     Kanji('験', ['ケン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/187/ken/_a.gif'),
     Kanji('答', ['こたーえる', 'こたーえ', 'トウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/118/kotae/_a.gif'),
     Kanji('考', ['かんがーえる', 'コウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/125/kangaeru/_a.gif'),
     Kanji('正', ['ただーしい', 'セイ', 'ショウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/77/tadashii/_a.gif'),
     Kanji('丸', ['まるーめる', 'まるーい', 'まる', 'ガン'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/3/maru/_a.gif'),
     Kanji('不', ['フ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/1/fu/_a.gif'),
     Kanji('同', ['おなーじ', 'ドウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/30/onaji/_a.gif'),
     Kanji('政', ['セイ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/66/sei/_a.gif'),
     Kanji('治', ['おさーめる', 'なおーる', 'なおーす', 'ジ', 'チ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/85/ji/_a.gif'),
     Kanji('経', ['へーる', 'ケイ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/120/kei/_a.gif'),
     Kanji('済', ['すーむ', 'すーます', 'サイ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/85/sumu/_a.gif'),
     Kanji('歴', ['レキ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/77/reki/_a.gif'),
     Kanji('史', ['シ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/30/shi/_a.gif'),
     Kanji('国', ['くに', 'コク'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/31/kuni/_a.gif'),
     Kanji('王', ['オウ'],
           4, 'http://www.nihongo.aikidoka.ru/image/kanji/96/_a.gif'))
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''),
     # Kanji('', [''], 4, ''))

word_list = (Word('働く', 'はたらく', 'работать'),
             Word('工場', 'こうじょう', 'завод'),
             Word('大家', 'おおや', 'домовладелец'),
             Word('家', 'いえ', 'дом'),
             Word('家ちん', 'やちん', 'квартплата'),
             Word('せいじ家', 'せいじか', 'политик'),
             Word('作家', 'さっか', 'автор'),
             Word('家族', 'かぞく', 'семья'),
             Word('一族', 'いちぞく', 'родня, родственник, клан'),
             Word('兄', 'あに', 'старший брат'),
             Word('父兄', 'ふけい', 'старшие члены семьи'),
             Word('ぎ兄', 'ぎけい', 'старший сводный брат'),
             Word('兄弟', 'きょうだい', 'братья'),
             Word('弟', 'おとうと', 'младший брат'),
             Word('ぎ弟', 'ぎてい', 'младший сводный брат'),
             Word('お兄さん', 'おにいさん', 'старший брат (обращение, уважительно)'),
             Word('姉', 'あね', 'старшая сестра'),
             Word('妹', 'いもうと', 'младшая сестра'),
             Word('ぎりの姉', 'ぎりのあね', 'старшая сводная сестра'),
             Word('姉妹', 'しまい', 'сёстры'),
             Word('三人姉妹', 'さんにんしまい', 'три сестры'),
             Word('お姉さん', 'おねえさん', 'старшая сестра (обращение, уважительно)'),
             Word('私', 'わたし', 'я'),
             Word('私立大学', 'しりつだいがく', 'частный колледж / университет'),
             Word('子どもが育つ', 'こどもがそだつ', 'дети растут'),
             Word('花を育てる', 'はなをそだてる', 'выращивать цветы'),
             Word('子育て', 'こそだて', 'воспитание'),
             Word('体育', 'たいいく', 'физкультура'),
             Word('文学部', 'ぶんがくぶ', 'филологический факультет'),
             Word('バレー部', 'バレーぶ', 'балетный кружок'),
             Word('部下', 'ぶか', 'подчиненный'),
             Word('部長', 'ぶちょう', 'директор отдела, начальник'),
             Word('本屋', 'ほんや', 'книжный магазин'),
             Word('花屋', 'はなや', 'Цветочный магазин'),
             Word('屋ね', 'やね', 'Крыша'),
             Word('屋上', 'おくじょう', 'Крыша (плоская, как в японских школах'),
             Word('部屋', 'へや', 'Комната'),
             Word('広い部屋', 'ひろいへや', 'Широкая комната'),
             Word('道が広がる', 'みちがひろがる', 'Широкая дорога'),
             Word('新聞を広げる', 'しんぶんをひろげる', 'Развернуть газету'),
             Word('広大な土地', 'こうだいなとち', 'Дорогой (большой, обширный) участок земли'),
             Word('せが低い', 'せがひくい', 'Низкий рост (букв. "спина низкая")'),
             Word('低下', 'ていか', 'деградация, спад, понижение'),
             Word('低学年', 'ていがくねん', 'нижняя ступень начальной школы'),
             Word('高低', 'こうてい', 'высокий и низкий'),
             Word('緑', 'みどり', 'зеленый'),
             Word('緑色', 'みどりいろ', 'зеленый цвет'),
             Word('緑茶', 'りょくちゃ', 'зеленый чай'),
             Word('新緑', 'しんりょく', 'молодая листва'),
             Word('静かな部屋', 'しずかなへや', 'в комнате тихая / тихая комната'),
             Word('れい静な人', 'れいせいなひと', 'хладнокровный'),
             Word('静電気', 'せいでんき', 'статическое электричество'),
             Word('学校に近い', 'がっこうにちかい', 'близко к школе'),
             Word('川に地下ずく', 'かわにちかずく', 'приближаться к реке'),
             Word('近所', 'きんじょ', 'близкое место'),
             Word('さい近', 'さいきん', 'недавно, в последнее время'),
             Word('近年', 'きんねん', 'ближайшие годы'),
             Word('駅から遠い', 'えきからとおい', 'далеко от станции'),
             Word('遠足', 'えんそく', 'пешая экскурсия'),
             Word('ぼう遠きょう', 'ぼうえんきょう', 'телескоп'),
             Word('友だちに会う', 'ともだちにあう', 'встречаться с друзьями'),
             Word('入会', 'にゅうかい', 'поступать на работу / начинать работу'),
             Word('会話', 'かいわ', 'диалог'),
             Word('スポーツ大会', 'スポーツたいかい', 'спортивное мероприятие'),
             Word('会社', 'かいしゃ', 'компания, фирма'),
             Word('入社しき', 'にゅうしゃしき', 'церемония поступления на фирму (работать)'),
             Word('本社', 'ほんしゃ', 'главный офис'),
             Word('じん社', 'じんじゃ', 'храм (синт.)'),
             Word('働く', 'はたらく', 'работать'),
             Word('ろう働', 'ろうどう', 'труд'),
             Word('ケーキを作る', 'ケーキをつくる', 'готовить торт'),
             Word('作しゃ', 'さくしゃ', 'автор'),
             Word('名作', 'めいさく', 'шедевр'),
             Word('作ぎょう', 'さぎょう', 'работа, объем работ'),
             Word('人工のいけ', 'じんこうのいけ', 'искусственный пруд'),
             Word('工学部', 'こうがくぶ', 'инженерные работы / инженерное отделение в универе'),
             Word('工作', 'こうさく', 'строительство, инженерные работы'),
             Word('工じ', 'こうじ', 'строительные работы (на дороге, например)'),
             Word('広場', 'ひろば', 'площадь'),
             Word('出場', 'しゅつじょう', 'выход на сцену'),
             Word('会場', 'かいじょう', 'место встречи'),
             Word('パーティーが始まる', 'パーティーがはじまる', 'вечеринка начинается'),
             Word('勉強を始める', 'べんきょうをはじめる', 'начинаю учебу'),
             Word('始ぎょうしき', 'しぎょうしき', 'церемония открытия'),
             Word('年始', 'ねんし', 'начало года'),
             Word('しごとが終わる', 'しごとがおわる', 'работа заканчивается'),
             Word('食じを終える', 'しょくじをおえる', 'окончить трапезу'),
             Word('終りょう', 'しゅうりょう', 'завершение чего-то'),
             Word('終日', 'しゅうじつ', 'целый день (что-то происходило в течение всего дня)'),
             Word('店', 'みせ', 'магазин'),
             Word('店いん', 'てんいん', 'продавец'),
             Word('本店', 'ほんてん', 'главный магазин / офис'),
             Word('し店', 'してん', 'филиал'),
             Word('きっさ店', 'きっさてん', 'кафе'),
             Word('お客さん', 'おきゃくさま', 'покупатель (уваж.)'),
             Word('来客', 'らいきゃく', 'посетитель, гость'),
             Word('客間', 'きゃくま', 'гостиная'),
             Word('父親', 'ちちおや', 'отец'),
             Word('母親', 'ははおや', 'мать'),
             Word('親子', 'おやこ', 'родители и дети'),
             Word('りょう新', 'りょうしん', 'родители'),
             Word('親友', 'しんゆう', 'близкий друг'),
             Word('親切　（な）', 'しんせつ', 'добрый, доброжелательный'),
             Word('切る', 'きる', 'резать'),
             Word('大切', 'たいせつ', 'важный, ценный, дорогой'),
             Word('切手', 'きって', 'почтовая марка'),
             Word('売る', 'うる', 'продавать'),
             Word('安売り', 'やすうり', 'продавать по дешевке'),
             Word('当てる', 'あてる', 'попадать, совпадать'),
             Word('よそうを当てる', 'よそうをあてる', 'оправдывать ожидания, соответствовать ожиданиям'),
             Word('べん当', 'べんとう', 'бэнто (обед в упаковке/коробочке)'),
             Word('当日', 'とうじつ', 'назначенный, тот самый день'),
             Word('本当', 'ほんとう', 'правда'),
             Word('品物', 'しなもの', 'товары'),
             Word('品かず', 'しなかず', 'ассортимент'),
             Word('手品', 'てじな', 'фокус, жульничество'),
             Word('手品を使う', 'てじなをつかう', 'показывать фокусы'),
             Word('食品', 'しょくひん', 'продовольственные товары'),
             Word('しょう品', 'しょうひん', 'товары / товары одного наименования / позиция'),
             Word('上品', 'じょうひん', 'вещь высшего качества'),
             Word('下品', 'げひん', 'низость, пошлость, вульгарность'),
             Word('上品　（な）', 'じょうひん　（な）', 'элегантный, изящный, утонченный'),
             Word('下品　（な）', 'げひん　（な）', 'низкий, пошлый, вульгарный'),
             Word('作品', 'さくひん', 'рукопись (лит.)'),
             Word('便り', 'たより', 'вести, известия, письмо'),
             Word('便利', 'べんり', 'удобный'),
             Word('便き', 'べんき', 'ночной горшок'),
             Word('こう空便', 'こうくうびん', 'авиапочта'),
             Word('ゆう便きょく', 'ゆうびんきょく', 'почтовое отделение'),
             Word('利用', 'りよう', 'использование'),
             Word('利子', 'りし', 'проценты (н-р, по вкладам)'),
             Word('使う', 'つかう', 'использовать'),
             Word('使い方', 'つかいかた', 'способ применения'),
             Word('大使', 'たいし', 'посол'),
             Word('使用', 'しよう', 'применение'),
             Word('銀色', 'ぎんいろ', 'серебристый цвет'),
             Word('白い', 'しろい', 'белый'),
             Word('白黒', 'しろくろ', 'черно-белый'),
             Word('黒い', 'くろい', 'черный'),
             Word('白鳥', 'はくちょう', 'лебедь'),
             Word('黒こしょう', 'くろこしょう', 'черный перец'),
             Word('まっ黒', 'まっくろ', 'совершенно черный'),
             Word('黒字', 'くろじ', 'положительное сальдо, бездефицитный баланс'),
             Word('黒ばん', 'こくばん', 'классная (черная) доска'),
             Word('紙', 'かみ', 'бумага'),
             Word('紙コップ', 'かみコップ', 'бумажный стаканчик'),
             Word('紙ひ行き', 'かみひこうき', 'бумажный самолетик'),
             Word('おり紙', 'おりがみ', 'оригами'),
             Word('コピー用紙', 'コピーようし', 'копировальная бумага'),
             Word('新聞紙', 'しんぶんし', 'газетная бумага'),
             Word('朝', 'あさ', 'утро'),
             Word('毎朝', 'まいあさ', 'каждое утро'),
             Word('朝日', 'あさひ', 'утренний свет'),
             Word('朝食', 'ちょうしょく', 'завтрак'),
             Word('朝晩', 'あさばん', 'утро и вечер'),
             Word('晩ごはん', 'ばんごはん', 'ужин'),
             Word('今晩', 'こんばん', 'этот вечер'),
             Word('今朝', 'けさ', 'сегодня утром'),
             Word('昼', 'ひる', 'день'),
             Word('昼食', 'ちゅうしょく', 'обед/второй завтрак'),
             Word('夜', 'よる', 'вечер, ночь'),
             Word('夜道', 'よみち', 'ночная, вечерняя дорога'),
             Word('夜中', 'よなか', 'полночь'),
             Word('今夜', 'こんや', 'этот вечер, эта ночь'),
             Word('しん夜', 'しんや', 'глубокая ночь'),
             Word('夜食', 'やしょく', 'ужин'),
             Word('名前', 'なまえ', 'имя'),
             Word('前', 'まえ', 'перед'),
             Word('前後', 'ぜんご', 'впереди и позади'),
             Word('前半', 'ぜんはん', 'первая половина'),
             Word('後半', 'こうはん', 'вторая половина'),
             Word('服の前後ろ', 'ふくのまえうしろ', 'перед и зад (у одежды)'),
             Word('後ろ', 'うしろ', 'позади'),
             Word('後', 'あと', 'после'),
             Word('午前', 'ごぜん', 'время до полудня'),
             Word('午後', 'ごご', 'время после полудня'),
             Word('午前中', 'ごぜんちゅう', 'в течение первой половины дня'),
             Word('しょう午', 'しょうご', 'полдень'),
             Word('早い', 'はやい', 'ранний'),
             Word('早く', 'はやく', 'рано'),
             Word('早口　（な）', 'はやくち　（な）', 'быстроговорящий (человек)'),
             Word('早朝', 'そうちょう', 'ранее утро'),
             Word('荷物', 'にもつ', 'багаж'),
             Word('手荷物', 'てにもつ', 'ручная кладь'),
             Word('送る', 'おくる', 'отправлять, посылать'),
             Word('送しん', 'そうしん', 'отправление, передача'),
             Word('見送り', 'みおくり', 'провожать взглядом'),
             Word('送べつ会', 'そうべつかい', 'прощальный вечер'),
             Word('帰宅', 'きたく', 'возвращение домой'),
             Word('住宅', 'じゅうたく', 'квартира, жилой дом'),
             Word('お宅', 'おたく', 'дом (уваж.)'),
             Word('急いで', 'いそいで', 'поспешно, торопливо'),
             Word('急行', 'きゅうこう', 'скорый (н-р, поезд)'),
             Word('急　（な）', 'きゅう　（な）', 'срочный, спешный, безотлагательный'),
             Word('きゅう急車', 'きゅうきゅうしゃ', 'машина скорой помощи'),
             Word('速い', 'はやい', 'быстрый'),
             Word('速さ', 'はやさ', 'быстрота'),
             Word('速ど', 'そくど', 'скорость'),
             Word('時速', 'じそく', 'скорость ... в час'),
             Word('速たつ', 'そくたつ', 'экспресс-доставка'),
             Word('遅れる', 'おくれる', ''),
             Word('時間に遅れる', 'じかんにおくれる', 'опаздывать (ко времени)'),
             Word('電車が遅れる', 'でんしゃがおくれる', 'поезд задерживается, опаздывает'),
             Word('遅こく', 'ちこく', 'явка с опозданием'),
             Word('重なる', 'かさなる', 'нагромождать друг на друга'),
             Word('よていが重なる', 'よていがかさなる', 'планы навалились'),
             Word('気が重い', 'きがおもい', 'тяжелый дух (плохое настроение)'),
             Word('体重', 'たいじゅう', 'вес тела'),
             Word('軽い', 'かるい', 'легкий'),
             Word('口が軽い', 'くちがかるい', 'болтун'),
             Word('軽やかにあるく', 'かろやかにあるく', 'идти легкой походкой'),
             Word('軽食', 'けいしょく', 'легкая еда'),
             Word('住む', 'すむ', 'жить, проживать'),
             Word('住宅がい', 'じゅうたくがい', 'жилой квартал'),
             Word('高い所', 'たかいところ', 'высокое место'),
             Word('住所', 'じゅうしょ', 'место проживания'),
             Word('場所', 'ばしょ', 'место'),
             Word('何か所', 'なんかしょ', 'сколько мест(а)?'),
             Word('長所', 'ちょうしょ', 'сильные стороны'),
             Word('短所', 'たんしょ', 'слабые стороны'),
             Word('田中様', 'たなかさま', 'Господин Танака (очень! уважительно'),
             Word('店内の様子', 'てんないのようす', 'внутри магазина'),
             Word('もち主', 'もちぬし', 'владелец, собственник'),
             Word('主に', 'おもに', 'главным образом, в основном'),
             Word('主（な）', '主（な）', 'главный'),
             Word('ご主人', 'ごしゅじん', 'хозяин, господин, муж (уваж.)'),
             Word('一番', 'いちばん', 'самый'),
             Word('何番', 'なんばん', 'который? какой (номер)?'),
             Word('交番', 'こうばん', 'полицейская будка'),
             Word('当番', 'とうばん', 'дежурство'),
             Word('地名', 'ちめい', 'топоним'),
             Word('地上', 'ちじょう', 'над землей, на земле'),
             Word('番地', 'ばんち', 'номер дома'),
             Word('地みな色', 'じみないろ', 'простой, скромный, неброский цвет'),
             Word('電話番号', 'でんわばんごう', 'номер телефона'),
             Word('１０１号室', '101ごうしつ', 'комната номер 101'),
             Word('しん号', 'しんごう', 'сигнал светофора'),
             Word('年号', 'ねんごう', 'девиз правления'),
             Word('号外', 'ごうがい', 'спецвыпуск'),
             Word('東京', 'とうきょう', 'Токио'),
             Word('京都', 'きょうと', 'Киото'),
             Word('京ひん', 'けいひん', 'Кэйхин (регион, Токио + Йокогама)'),
             Word('都内', 'とない', 'в городе (о Токио, Осаке, Киото)'),
             Word('都会', 'とかい', 'город'),
             Word('住めば都', 'すめばみやこ', 'пословица как "всяк кулик свое болото хвалит" (буквально: место, где живешь,'
                                    ' кажется столицей'),
             Word('道をあるく', 'みちをあるく', 'идти по дороге'),
             Word('道ろ', 'どうろ', 'дорога, шоссе'),
             Word('北かい道', 'ほっかいどう', 'Хоккайдо'),
             Word('道ぐ', 'どうぐ', 'средство, орудие'),
             Word('大阪府', 'おおさかふ', 'префектура Осака'),
             Word('京都府', 'きょうとふ', 'префектура Киото'),
             Word('山口県', 'やまぐちけん', 'префектура Ямагучи'),
             Word('青森県', 'あおもりけん', 'префектура Аомори'),
             Word('岩手県', 'いわてけん', 'префектура Ивате'),
             Word('市場', 'いちば', 'рынок'),
             Word('市やく所', 'しやくしょ', 'городское (муницип.) управление'),
             Word('市内', 'しない', 'внутри города'),
             Word('一都一道二府四十三県', 'いっといちどうにふよんじゅうさんけん', 'Один "то" (Токио), один "до" (Хоккайдо), '
                                                      'два "фу" (Осака и Киото) и 43 кен (префектуры)'),
             Word('二十三区', 'にじゅうさんく', 'двадцать три района'),
             Word('区長', 'くちょう', 'глава района/города'),
             Word('区内', 'くない', 'в границах района'),
             Word('村', 'むら', 'деревня'),
             Word('村長', 'そんちょう', 'сельский староста'),
             Word('市町村', 'しちょうそん', 'города, городки и деревни'),
             Word('毎日', 'まいにち', 'каждый день'),
             Word('毎年', 'まいとし', 'каждый год'),
             Word('毎かい', 'まいかい', 'каждый раз'),
             Word('毎週', 'まいしゅう', 'каждую неделю'),
             Word('週休', 'しゅうきゅう', 'свободные от работы дни в неделе'),
             Word('二週間', 'にしゅうかん', 'две недели'),
             Word('週まつ', 'しゅうまつ', 'конец недели, уикенд'),
             Word('来週', 'らいしゅう', 'следующая неделя'),
             Word('テレビに映る', 'テレビにうつる', 'появиться на TV'),
             Word('映す', 'うつす', 'отображаться, появляться'),
             Word('映画', 'えいが', 'фильм, кино'),
             Word('画家', 'がか', 'художник'),
             Word('パソコンの画めん', 'パソコンのがめん', 'экран компьютера'),
             Word('まん画', 'まんが', 'манга'),
             Word('画すう', 'かくすう', 'кол-во черт в иероглифе'),
             Word('計画', 'けいかく', 'план, программа, проект'),
             Word('地図', 'ちず', 'карта'),
             Word('図画工作', 'ずがこうさく', 'рисование, черчение (как школьный предмет)'),
             Word('しょく物図かん', 'しょくぶつずかん', 'ботаническая книга с картинками'),
             Word('図書館', 'としょかん', 'библиотека'),
             Word('映画館', 'えいがかん', 'кинотеатр'),
             Word('大使館', 'たいしかん', 'посольство'),
             Word('はく物館', 'はくぶつかん', 'музей'),
             Word('公', 'おおやけ', 'публичный, открытый, общественный'),
             Word('公立', 'こうりつ', 'в сочетаниях: общественный, публичный; муниципальный, '
                                'префектуральный (об учреждениях)'),
             Word('主人公', 'しゅじんこう', 'протагонист / хозяин дома, глава семьи'),
             Word('映画の公開', 'えいがのこうかい', ''),
             Word('公園', 'こうえん', 'релиз фильма'),
             Word('ゆう園地', 'ゆうえんち', 'парк, площадка для игр или гулянья'),
             Word('動物園', 'どうぶつえん', 'зоопарк'),
             Word('ようち園', 'ようちえん', 'детсад'),
             Word('夫', 'おっと', 'муж'),
             Word('田中夫妻', 'たなかふさい', 'супруги Танака'),
             Word('夫ふ', 'ふうふ', 'муж и жена, супружеская пара'),
             Word('夫人', 'ふじん', 'вежл. супруга, жена'),
             Word('妻', 'つま', 'жена'),
             Word('妻子', 'さいし', 'жена и дети, семья'),
             Word('あい妻家', 'あいさいか', 'любящий муж'),
             Word('特べつ　（な）', 'とくべつ　（な）', 'особенный'),
             Word('特売', 'とくばい', 'продажа по дешевке'),
             Word('特に', 'とくに', 'в особенности'),
             Word('特急', 'とっきゅう', 'экспресс'),
             Word('思う', 'おもう', 'думать, заботиться'),
             Word('思い', 'おもい', 'мысль'),
             Word('思い出', 'おもいで', 'воспоминания'),
             Word('思しゅんき', 'ししゅんき', 'половая зрелость'),
             Word('料金', 'りょうきん', 'плата'),
             Word('食料', 'しょくりょう', 'еда, продукты питания'),
             Word('む料', 'むりょう', 'бесплатно'),
             Word('し料', 'しりょう', 'материалы, данные'),
             Word('料理', 'りょうり', 'кухня'),
             Word('理ゆう', 'りゆう', 'причина, повод'),
             Word('物理', 'ぶつり', 'физика'),
             Word('理けい', 'りけい', '"естественники" (как челы из ИЕНиМа)'),
             Word('有料', 'ゆうりょう', 'платный'),
             Word('有名人', 'ゆうめいじん', 'знаменитость'),
             Word('有力（な）', 'ゆうりょく　（な）', 'влиятельный, веский'),
             Word('有利　（な）', 'ゆうり　（な）', 'выгодный, полезный'),
             Word('西洋', 'せいよう', 'Запад (Европа и Америка)'),
             Word('東洋', 'とうよう', 'Восток (в широком смысле)'),
             Word('洋楽', 'ようがく', 'западноевропейская музыка'),
             Word('洋画', 'ようが', 'живопись в западном стиле'),
             Word('せい服', 'せいふく', 'форменная одежда, форма'),
             Word('洋服', 'ようふく', 'европейская одежда'),
             Word('わ服', 'わふく', 'японская одежда'),
             Word('私服', 'しふく', 'штатский костюм'),
             Word('衣食住', 'いしょくじゅう', 'одежда, пища и кров'),
             Word('衣服', 'いふく', 'одежда'),
             Word('衣料品', 'いりょうひん', 'одежда, предметы одежды'),
             Word('衣がえ', 'ころもがえ', 'смена одежды по сезону'),
             Word('短い', 'みじかい', 'короткий'),
             Word('短気', 'たんき', 'вспыльчивость'),
             Word('長短', 'ちょうたん', 'достоинства и недостатки'),
             Word('かみの毛', 'かみのけ', 'волосы на голове'),
             Word('まつ毛', 'まつげ', 'ресницы'),
             Word('まゆ毛', 'まゆげ', 'брови'),
             Word('毛ふ', 'もうふ', 'плед, шерст. одеяло'),
             Word('よう毛', 'ようもう', 'шерсть'),
             Word('毛糸', 'けいと', 'шерсть (пряжа)'),
             Word('はりと糸', 'はりといと', 'игла и нить'),
             Word('水玉', 'みずたま', 'капля воды'),
             Word('十円玉', 'じゅうえんだま', 'монета 10 йен'),
             Word('玉ねぎ', 'たまねぎ', 'лук'),
             Word('星が光る', 'ほしがひかる', 'звезды сияют'),
             Word('月の光', 'つきのひかり', 'лунный свет'),
             Word('日光', 'にっこう', 'солнечный свет '),
             Word('電光けいじばん', 'でんこうけいじばん', 'электронная доска объявлений'),
             Word('かん光', 'かんこう', 'светочувствительность'),
             Word('鉄', 'てつ', 'железо'),
             Word('地下鉄', 'ちかてつ', 'метро'),
             Word('鉄分', 'てつぶん', 'содержание железа'),
             Word('鉄道', 'てつどう', 'железная дорога'),
             Word('駅', 'えき', 'станция'),
             Word('駅いん', 'えきいん', 'работник станции'),
             Word('駅長', 'えきちょう', 'начальник станции'),
             Word('二つ目の駅', 'ふたつめのえき', 'вторая станция'),
             Word('タクシーに乗る', 'タクシーにのる', 'садиться в такси'),
             Word('荷物を乗せる', 'にもつをのせる', 'положить вещи'),
             Word('タクシー乗り場', 'タクシーのりば', 'стоянка такси'),
             Word('乗客', 'じょうきゃく', 'пассажир'),
             Word('電車を降りる', 'でんしゃをおりる', 'сойти с поезда'),
             Word('荷物を降ろす', 'にもつをおろす', 'разгрузить / спустить багаж'),
             Word('雨が降る', 'あめがふる', 'идет дождь'),
             Word('降車口', 'こうしゃぐち', 'выход (для высадки пассажиров)'),
             Word('ドアが開く', 'ドアがあく', 'открыть дверь'),
             Word('店を開く', 'みせをひらく', 'открыть магазин'),
             Word('ドアの開閉', 'ドアのかいへい', 'открывание и закрывание (двери)'),
             Word('開園', 'かいえん', 'открытие парка/сада'),
             Word('映画の公開', 'えいがのこうかい', 'показ фильма'),
             Word('開場時間', 'かいじょうじかん', 'время открвтия'),
             Word('本を閉じる', 'ほんをとじる', 'закрыть книгу'),
             Word('閉店セール', 'へいてんセール', 'распродажа в честь закрытия магазина'),
             Word('発明', 'はつめい', 'изобретение'),
             Word('開発', 'かいはつ', 'разработка'),
             Word('発音', 'はつおん', 'произношение'),
             Word('発足', 'ほっそく', 'первый шаг (книжн.) / инаугурация'),
             Word('シャツを着る', 'シャツをきる', 'надеть футболку'),
             Word('着物', 'きもの', 'одежда, кимоно'),
             Word('着地', 'ちゃくち', 'приземление'),
             Word('一着', 'いっちゃく', 'один костюм (пара брюк)'),
             Word('上着', 'うわぎ', 'верхняя одежда'),
             Word('下着', 'したぎ', 'нижнее белье'),
             Word('道が交わる', 'みちがまじわる', 'дороги пересекаются'),
             Word('トランプを交ぜる', 'とランプを交ぜる', 'тасовать игральные карты'),
             Word('交さてん', '交りゅう', 'перекресток'),
             Word('交りゅう', 'こうりゅう', 'общение, взаимный обмен'),
             Word('車が通る', 'くるまがとおる', 'автомобиль проехал'),
             Word('大通り', 'おおどおり', 'главная дорога'),
             Word('通きん', 'つうきん', 'хождение на работу (+する）'),
             Word('通学', 'つうがく', 'хождение в школу (+する）'),
             Word('一方通行', 'いっぽうつうこう', 'одностороннее движение'),
             Word('バスが三台', 'バズがさんだい', 'три автобуса'),
             Word('台所', 'だいどころ', 'кухня'),
             Word('トラックの荷台', 'トラックのにだい', 'кузов грузовика'),
             Word('高台', 'たかだい', 'возвышенность'),
             Word('台風', 'たいふう', 'тайфун'),
             Word('急に止まる', 'きゅうにとまる', 'внезапно остановиться'),
             Word('車を止める', 'くるまをとめる', 'остановить машину'),
             Word('きん止', 'きんし', 'запрет'),
             Word('七色', 'なないろ', 'семь цветов или призматические цвета (в физике)'),
             Word('色紙', 'いろがみ', 'цветная бумага'),
             Word('特色', 'とくしょく', 'особенность, черта характера'),
             Word('赤い', 'あかい', 'красный'),
             Word('赤ペン', 'あかペン', 'красная ручка'),
             Word('赤', 'あか', 'красный цвет, красное'),
             Word('赤道', 'せきどう', 'экватор'),
             Word('赤はん', 'せきはん', 'вареный рис с красной фасолью'),
             Word('黄色', 'きいろ', 'желтый цвет'),
             Word('黄金', 'おうごん', 'золото (прям. и переносн.) в сочетаниях'),
             Word('らん黄', 'らんおう', 'желток'),
             Word('青い海', 'あおいうみ', 'синий океан'),
             Word('青しん号', 'あおしんごう', 'зеленый свет светофора'),
             Word('青空', 'あおぞら', 'голубое небо, синева'),
             Word('青年', 'せいねん', 'юноша, юнец'),
             Word('青春', 'せいしゅん', 'весна жизни, юность'),
             Word('病気', 'びょうき', 'болезнь'),
             Word('病院', 'びょういん', 'больница'),
             Word('入院', 'にゅういん', 'поступление в больницу (лечь в больницу)'),
             Word('たい院', 'たいいん', 'выписывание (из больницы)'),
             Word('院長', 'いんちょう', 'главврач'),
             Word('通院', 'つういん', 'регулярное посещение больницы (+する）'),
             Word('大学院生', 'だいがくいんせい', 'аспирант'),
             Word('寺院', 'じいん', 'храм'),
             Word('医しゃ', 'いしゃ', 'врач'),
             Word('医学', 'いがく', 'медицина'),
             Word('科目', 'かもく', 'предмет, курс, отрасль'),
             Word('理科', 'りか', 'естествознание'),
             Word('科学', 'かがく', 'наука'),
             Word('学科', 'がっか', 'курс (наук), дисциплина, факультет'),
             Word('内科', 'ないか', 'терапевт'),
             Word('外科', 'げか', 'хирургия'),
             Word('薬を飲む', 'くすりをのむ', 'пить лекарство'),
             Word('かぜ薬', 'かぜぐすり', 'лекарство от простуды'),
             Word('薬きょく', 'やっきょく', 'аптека'),
             Word('ずつう薬', 'ずつうやく', 'головная боль'),
             Word('目薬', 'めぐすり', 'глазные капли'),
             Word('バズを待つ', 'バスをまつ', 'ждать автобус'),
             Word('待ち時間', 'まちじかん', 'время ожидания'),
             Word('き待', 'きたい', 'ожидания, надежды'),
             Word('気が合う', 'きがあう', 'ладить друг с другом'),
             Word('こたえ合わせ', 'こたえあわせ', 'проверить ответ'),
             Word('合かく', 'ごうかく', 'соответствие требования (+する）'),
             Word('待合しつ', 'まちあいしつ', 'зал ожидания'),
             Word('会計', 'かいけい', 'счет, бюджет, бухучет'),
             Word('合計', 'ごうけい', 'итог, итого'),
             Word('計さん', 'けいさん', 'счет, расходы, вычисления '),
             Word('時計', 'とけい', 'часы'),
             Word('研しゅう', 'けんしゅう', 'совершенствование в знаниях, научное исследование'),
             Word('研究', 'けんきゅう', 'изучение, научная работа, исследование'),
             Word('研究しゃ', 'けんきゅうしゃ', 'исследователь, ученый'),
             Word('研究会', 'けんきゅうかい', 'научно-исследовательское общество, научный кружок'),
             Word('研究所', 'けんきゅうじょ', 'научно-исследовательский институт, лаборатория'),
             Word('じゆう研究', 'じゆうけんきゅう', 'свободные занятия (в школах)'),
             Word('研究計画書', 'けんきゅうけいかくしょ', 'план исследования'),
             Word('ゆめを語る', 'ゆめをかたる', 'рассказывать сон'),
             Word('語学', 'ごがく', 'лингвистика'),
             Word('日本語', 'にほんご', 'японский язык'),
             Word('たん語', 'たんご', 'слово'),
             Word('作文', 'さくぶん', 'сочинение'),
             Word('文学部', 'ぶんがくぶ', 'лит. факультет'),
             Word('ちゅう文', 'ちゅうもん', 'заказ'),
             Word('物語', 'ものがたり', 'рассказ, история'),
             Word('英さい', 'えいさい', 'талант'),
             Word('英語', 'えいご', 'английский язык'),
             Word('文化', 'ぶんか', 'культура'),
             Word('化学', 'かがく', 'химия'),
             Word('化石', 'かせき', 'окаменелость'),
             Word('へん化', 'へんか', 'изменения'),
             Word('化しょう', 'けしょう', 'косметика, макияж'),
             Word('化しょう品', 'けしょうひん', 'косметические товары'),
             Word('数', 'かず', 'число'),
             Word('数える', 'かぞえる', 'считать'),
             Word('数学', 'すうがく', 'математика'),
             Word('数字', 'すうじ', 'цифра'),
             Word('数人', 'すうにん', 'несколько человек'),
             Word('心', 'こころ', 'сердце'),
             Word('安心', 'あんしん', 'спокойствие'),
             Word('中心', 'ちゅうしん', 'центр'),
             Word('若い', 'わかい', 'молодой'),
             Word('若もの', 'わかもの', 'молодой человек, юноша'),
             Word('人が集まる', 'ひとがあつまる', 'люди собираются вместе'),
             Word('切手を集める', 'きってをあつめる', 'коллекционировать марки'),
             Word('集合', 'しゅうごう', 'сбор, встреча'),
             Word('集中', 'しゅうちゅう', 'сосредоточие (+する）'),
             Word('文集', 'ぶんしゅう', 'сборник сочинений'),
             Word('ぼ集', 'ぼしゅう', 'вербовка'),
             Word('知り合う', 'しりあう', 'знакомиться'),
             Word('知しき', 'ちしき', 'знания'),
             Word('知人', 'ちじん', 'знакомый'),
             Word('通知', 'つうち', 'сообщение, уведомление'),
             Word('お酒', 'おさけ', 'алкоголь'),
             Word('い酒屋', 'いざかや', 'идзакая, японский трактир, бар, питейная'),
             Word('日本酒', 'にほんしゅ', 'японский алкоголь'),
             Word('飲酒うんてん', 'いんしゅうんてん', 'вождение в нетрезвом виде'),
             Word('歌を歌う', 'うたをうたう', 'петь песни'),
             Word('はな歌', 'はなうた', 'мурлыканье, напевание с закрытым ртом'),
             Word('歌手', 'かしゅ', 'певец'),
             Word('校歌', 'こうか', 'гимн школы'),
             Word('大きな声', 'おおきなこえ', 'громкий голос'),
             Word('話し声', 'はなしごえ', 'звук разговора'),
             Word('なき声', 'なきごえ', 'звук плача'),
             Word('音声', 'おんせい', 'звук, голос (в общем и техническом смысле)'),
             Word('楽しい', 'たのしい', 'веселый'),
             Word('楽な仕事', 'らくなしごと', 'легкая работа, работа в удовольствие'),
             Word('楽しょう', 'らくしょう', 'легкая победа'),
             Word('楽き', 'がっき', 'музыкальный инструмент'),
             Word('音楽', 'おんがく', 'музыка'),
             Word('楽園', 'らくえん', 'рай, райский сад'),
             Word('声楽', 'せいがく', 'вокал, вокальная музыка'),
             Word('スープの味', 'スープのあじ', 'вкус супа'),
             Word('味見', 'あじみ', 'дегустация'),
             Word('ちょう味料', 'ちょうみりょう', 'приправы'),
             Word('い味', 'いみ', 'смысл, значение'),
             Word('油', 'あぶら', 'жидкое масло, горючее, сало, жир'),
             Word('石油ストーブ', 'せきゆストーブ', 'масляная печь'),
             Word('しょう油', 'しょうゆ', 'соевый соус'),
             Word('ラー油', 'ラーゆ', 'соус/масло чили'),
             Word('太いベルト', 'ふといベルト', 'толстый ремень'),
             Word('太る', 'ふとる', 'толстеть'),
             Word('太よう', 'たいよう', 'солнце'),
             Word('細長い部屋', 'ほそながいへや', 'прямая и длинная комната'),
             Word('細い', 'ほそい', 'тонкий, узкий'),
             Word('細かいお金', 'こまかいおかね', 'мелочь, небольшое изменение'),
             Word('きゅうよ明細', 'きゅうよめいさい', 'платежная ведомость'),
             Word('皿', 'さら', 'тарелка, блюдо'),
             Word('小皿', 'こざら', 'блюдце, тарелочка'),
             Word('取り皿', 'とりざら', 'индивидуальная тарелка'),
             Word('はい皿', 'はいざら', 'пепельница'),
             Word('飯', 'めし', 'вареный рис, пища, еда'),
             Word('夕飯', 'ゆうはん', 'ужин'),
             Word('すい飯き', 'すいはんき', 'рисоварка'),
             Word('昼ご飯', 'ひるごはん', 'обед'),
             Word('麦', 'むぎ', 'общее название для колосовых культур'),
             Word('小麦', 'こむぎ', ''),
             Word('大麦', 'おおむぎ', 'ячмень'),
             Word('麦茶', 'むぎちゃ', 'ячменный чай'),
             Word('麦わらぼうし', 'むぎわらぼうし', 'соломенная шляпа'),
             Word('春休み', 'はるやすみ', 'весенние каникулы'),
             Word('立春', 'りっしゅん', 'начало весны (4-19 февраля)'),
             Word('春分の日', 'しゅんぶんのひ', 'день весеннего равноденствия (20 марта)'),
             Word('夏休み', 'なつやすみ', 'летние каникулы'),
             Word('しょ夏', 'しょか', 'начало лета'),
             Word('秋', 'あき', 'осень'),
             Word('秋分の日', 'しゅうぶんおひ', 'день осеннего равноденствия'),
             Word('立秋', 'りっしゅう', 'начало осени (7-23 августа)'),
             Word('冬', 'ふゆ', 'зима'),
             Word('ま冬', 'まふゆ', 'настоящая зима, разгар зимы'),
             Word('春夏秋冬', 'しゅんかしゅうとう', 'четыре времени года'),
             Word('空きカン', 'あきカン', 'пустая консервная банка'),
             Word('時間が空く', 'じかんがあく', 'свободное время'),
             Word('せきを空ける', 'せきをあける', 'освободить место'),
             Word('空', 'そら', 'небо'),
             Word('空のはこ', 'からのはこ', 'пустая коробка'),
             Word('空気', 'くうき', 'воздух'),
             Word('空こう', 'くうこう', 'аэропорт'),
             Word('火星', 'かせい', 'Марс'),
             Word('雲', 'くも', 'облако, туча'),
             Word('せきらん雲', 'せきらんうん', 'ливневые грозовые облака'),
             Word('夏が去る', 'なつがさる', 'лето заканчивается'),
             Word('去年', 'きょねん', 'прошлый год'),
             Word('か去', 'かこ', 'прошлое, минувшее'),
             Word('しょう去', 'しょうきょ', 'удаление, стирание'),
             Word('し去', 'しきょ', 'смерть, кончина'),
             Word('天気', 'てんき', 'погода'),
             Word('雨天', 'うてん', 'дождливая погода'),
             Word('天使', 'てんし', 'ангел'),
             Word('天空', 'てんくう', 'небо (книжн.)'),
             Word('晴天', 'せいてん', 'синее, ясное небо'),
             Word('空が晴れる', 'そらがはれる', 'небо проясняется'),
             Word('かい晴', 'かいせい', 'ясная, безоблачная погода'),
             Word('雪', 'ゆき', 'снег'),
             Word('雪国', 'ゆきぐに', 'снежная страна'),
             Word('大雪', 'おおゆき', 'сильный снегопад'),
             Word('新雪のゲレンデ', 'しんせつのゲレンデ', 'свежий снег на горноложном склоне'),
             Word('風速', 'ふうそく', 'скорость ветра'),
             Word('風車', 'ふうしゃ', 'ветряная мельница'),
             Word('洋風', 'ようふう', 'европейский стиль'),
             Word('和風', 'わふう', 'японский стиль'),
             Word('火を強める', 'ひをつよめる', 'добавить огня'),
             Word('強風', 'きょうふう', 'сильный ветер'),
             Word('力を弱める', 'ちからをよわめる', 'ослабить силу'),
             Word('体が弱い', 'からだがよわい', 'слабый здоровьем, хилый'),
             Word('弱小チーム', 'じゃくしょうチーム', 'слабая команда'),
             Word('強弱', 'きょうじゃく', 'сильный—слабый'),
             Word('暑さ', 'あつさ', 'жара, зной'),
             Word('もう暑日', 'もうしょび', 'чрезвычайно жаркий день'),
             Word('ひ暑地', 'ひしょち', 'летний курорт, место, где можно спастись от жары'),
             Word('暑中見まい', 'しょちゅうみまい', 'летняя поздравительная открытка'),
             Word('寒さ', 'さむさ', 'холод'),
             Word('寒気', 'さむけ', 'ощущение холода, озноб'),
             Word('ぼう寒', 'ぼうかん', 'защита от холода'),
             Word('旅', 'たび', 'путешествие, поездка'),
             Word('旅行', 'りょこう', 'путешествие, поездка'),
             Word('旅館', 'りょかん', 'гостиница, отель (традиц.)'),
             Word('旅ひ', 'りょひ', 'путевые расходы'),
             Word('荷物を持つ', 'にもつをもつ', 'иметь/держать багаж'),
             Word('気持ち', 'きもち', 'настроение'),
             Word('持ち物', 'もちもの', 'чьи-либл вещи / вещи, взятые с собой'),
             Word('持病', 'じびょう', 'хроническая болезнь'),
             Word('世の中', 'よのなか', 'мир, свет, жизнь'),
             Word('中世', 'ちゅうせい', 'средневековье'),
             Word('世間', 'せけん', 'люди, народ, общество'),
             Word('出世', 'しゅっせ', 'успех в жизни, успешная карьера'),
             Word('21世き', '21せいき', '21 век'),
             Word('世界', 'せかい', 'мир, свет, область'),
             Word('げん界', 'げんかい', 'предел, граница'),
             Word('げいのう界', 'げいのうかい', 'мир шоу-бизнеса'),
             Word('写る', 'うつる', 'отражаться, падать (тень)'),
             Word('ノートを写す', 'ノートうつす', 'делать заметки'),
             Word('写生', 'しゃせい', 'рисование с натуры （+する）'),
             Word('真夏', 'まなつ', 'середина, разгар лета'),
             Word('真心', 'まごころ', 'искренность, правдивость'),
             Word('写真', 'しゃしん', 'фотография'),
             Word('真空', 'しんくう', 'вакуум, пустота'),
             Word('真じつ', 'しんじつ', 'правда, истина, факт'),
             Word('船', 'ふね', 'судно, корабль'),
             Word('客船', 'きゃくせん', 'пассажирское судно'),
             Word('船長', 'せんちょう', 'капитан судна'),
             Word('風船', 'ふうせん', 'воздушный шар, надувной шарик'),
             Word('売り切れ', 'うりきれ', 'распроданный'),
             Word('便せん', 'びんせん', 'почтовая бумага'),
             Word('銀行', 'ぎんこう', 'банк'),
             Word('勉強', 'べんきょう', 'изучение, учеба'),
             Word('勉強家', 'べんきょうか', 'прилежный, старательный, работяга'),
             Word('きん勉', 'きんべん', 'старание'),
             Word('漢字', 'かんじ', 'кандзи, иероглиф'),
             Word('漢数字', 'かんすうじ', 'китайская цифра'),
             Word('漢わじてん', 'かんわじてん', 'японский толковый иероглифический словарь'),
             Word('漢方薬', 'かんぽうやく', 'кампояку (лекарственное средство)'),
             Word('宿', 'やど', 'дом, квартира, ночлег'),
             Word('宿題', 'しゅくだい', 'домашнее задание, нерешенный вопрос'),
             Word('宿はく', 'しゅくはく', 'ночевка, остановка на ночь'),
             Word('合宿', 'がっしゅく', 'совместное проживание, лагерь'),
             Word('新宿駅', 'しんじゅくえき', 'станция Синдзюку'),
             Word('題名', 'だいめい', 'заглавие'),
             Word('話題', 'わだい', 'тема, предмет (разговора, обсуждения и т.п.)'),
             Word('質問', 'しつもん', 'вопрос; запрос'),
             Word('せい質', 'せいしつ', 'характер, натура; природа, свойство, качество'),
             Word('問いにこたえる', 'といにこたえる', 'отвечать на вопрос'),
             Word('い見を問う', 'いけんをとう', 'получить мнение'),
             Word('問題', 'もんだい', 'вопрос, проблема'),
             Word('問題しゅう', 'もんだいしゅう', 'воркбук, набор проблем / вопросов'),
             Word('社会問題', 'しゃかいもんだい', 'социальные проблемы'),
             Word('学問', 'がくもん', 'учение, учёба, занятия, образование, эрудиция'),
             Word('英語を教える', 'えいごをおしえる', 'преподавать английский язык'),
             Word('日本語を教わる', 'にほんごをおそわる', 'обучаться японскому языку'),
             Word('教育', 'きょういく', 'образование; преподавание; просвещение'),
             Word('教室', 'きょうしつ', 'класс, классная комната'),
             Word('教科書', 'きょうかしょ', 'учебник'),
             Word('ぶっ教', 'ぶっきょう', 'буддизм'),
             Word('教じゅ', 'きょうじゅ', 'преподавание, обучение, профессор'),
             Word('研究室', 'けんきゅうしつ', 'лаборатория, кабинет (в учебном или научном заведении)'),
             Word('試みる', 'こころみる', 'пробовать; испытывать; проверять; пытаться; делать опыт'),
             Word('試す', 'ためす', 'испытывать; проверять; пробовать; экспериментировать'),
             Word('試験', 'しけん', 'экзамен, испытание, тест, интервью'),
             Word('試食', 'ししょく', 'проба пищи (+する）'),
             Word('試着', 'しちゃく', 'примерка (одежды)'),
             Word('試合', 'しあい', 'спорт. игра, матч; соревнование, состязание, турнир; партия'),
             Word('じっ験', 'じっけん', 'эксперимент'),
             Word('体験', 'たいけん', 'собственный опыт, личный опыт'),
             Word('問題に答える', 'もんだいにこたえる', 'решить вопрос'),
             Word('答え', 'こたえ', 'ответ, решение'),
             Word('かい答', 'かいとう', 'ответ, реакция, разъяснение'),
             Word('考える', 'かんがえる', 'обдумывать, мыслить, судить, догадываться'),
             Word('考え方', 'かんがえかた', 'мнение, точка зрения'),
             Word('考えごと', 'かんがえごと', 'размышления'),
             Word('さん考し料', 'さんこうしりょう', 'справочная информация'),
             Word('プラス思考', 'プラスしこう', 'позитивное мышление'),
             Word('正しい', 'ただしい', 'правильный, верный, честный'),
             Word('正かくな日本語', 'せいかくなにほんご', 'точный японский'),
             Word('正かい', 'せいかい', 'правильное понимание'),
             Word('正午', 'しょうご', 'полдень'),
             Word('正月', 'しょうがつ', 'Новый год'),
             Word('丸い', 'まるい', 'круглый'),
             Word('丸を付ける', 'まるをつける', 'пометить верный ответ кружочком'),
             Word('丸める', 'まるめる', 'придавать круглую форму'),
             Word('不便', 'ふべん', 'неудобство'),
             Word('不安', 'ふあん', 'беспокойство, нервозность'),
             Word('不合かく', 'ふごうかく', 'несоответствие требованиям, непригодность (напр. при приёме)'),
             Word('不思ぎな話', 'ふしぎなはなし', 'загадочная история'),
             Word('同じ', 'おなじ', 'одинаковый, такой же'),
             Word('同きゅう生', 'どうきゅうせい', 'одноклассник; сокурсник'),
             Word('合同', 'ごうどう', 'слияние, объединение, соединение; коалиция'),
             Word('同時', 'どうじ', 'одновременно'),
             Word('政治', 'せいじ', 'политика'),
             Word('政治家', 'せいじか', 'политик, политический деятель'),
             Word('政府', 'せいふ', 'правительство, администрация'),
             Word('国を治める', 'くにをおさめる', 'управлять государством'),
             Word('病気が治る', 'びょうきがなおる', 'поправиться от болезни'),
             Word('かぜを治す', 'かぜをなおす', 'вылечить простуду'),
             Word('治りょう', 'ちりょう', 'лечение, уход за больным'),
             Word('けがが完治する', 'けががかんちする', 'рана заживает'),
             Word('長い年月を経る', 'ながいねんげつをへる', 'годы идут / спустя много лет'),
             Word('経済', 'けいざい', 'экономика, хозяйство'),
             Word('経験', 'けいけん', 'опыт, практика'),
             Word('経えい', 'けいえい', 'управление, руководство, заведование; менеджмент'),
             Word('宿題が済む', 'しゅくだいがすむ', 'выполнить домашнее задание'),
             Word('食事を済ます', 'しょくじをすます', 'окончить трапезу '),
             Word('しゃっ金をへん済する', 'しゃっきんをへんさいする', 'погасить долг'),
             Word('歴史', 'れきし', 'история; прошлое'),
             Word('り歴書', 'りれきしょ', 'автобиография, послужной список, анкетные данные, резюме'),
             Word('学歴', 'がくれき', '[полученное] образование, школьное образование'),
             Word('日本史', 'にほんし', 'история Японии'),
             Word('世界史', 'せかいし', 'всемирная история'),
             Word('東洋史', 'とうようし', 'история Азии'),
             Word('西洋史', 'せいようし', 'история Западного мира'),
             Word('史学', 'しがく', 'история, изучение истории'),
             Word('国語', 'こくご', 'язык (какой-л. страны), родной язык'),
             Word('国せき', 'こくせき', 'гражданство; подданство'),
             Word('帰国', 'きこく', 'возвращение на родину'),
             Word('外国', 'がいこく', 'иностранное государство; заграница; зарубежье'),
             Word('国内', 'こくない', ''),
             Word('国歌を歌う', 'こっかをうたう', 'петь национальный гимн'),
             Word('中国', 'ちゅうごく', 'Китай'),
             Word('王様', 'おうさま', 'уваж. царь; король'))
# Word('', '', ''),
# Word('', '', ''),
# Word('', '', ''),
# Word('', '', ''),
# Word('', '', ''),
# Word('', '', ''),
# Word('', '', ''),
# Word('', '', ''),
# Word('', '', ''),
# Word('', '', ''),
# Word('', '', ''),
# Word('', '', ''),
# Word('', '', ''),
# Word('', '', ''),
# Word('', '', ''),
# Word('', '', ''),
# Word('', '', ''),
# Word('', '', ''), Word('', '', ''),
# Word('', '', ''),
# Word('', '', ''),
# Word('', '', ''),
# Word('', '', ''),
# Word('', '', ''),
# Word('', '', ''),
# Word('', '', ''), Word('', '', ''),
# Word('', '', ''),
# Word('', '', ''),
# Word('', '', ''),
# Word('', '', ''),
# Word('', '', ''),
# Word('', '', ''),
# Word('', '', '')


for kanji in kanji_list:
    for word in word_list:
        for symbol in word.word:
            if symbol == kanji.kanji:
                kanji.words.append(word)
